# Désactiver l'accès sans mot de passe (si tu as le temps)
allow_anonymous false
password_file /mosquitto/config/password_file

# Port standard
listener 1883

# Pas besoin de garder l'historique des messages MQTT
persistence false

# Sécurité réseau : On ne logue que les erreurs
log_dest stdout
log_type error
